#!/usr/bin/env python3
"""Generate a publication audit and exact non-self-referential manifest."""

from __future__ import annotations

import ast
import hashlib
import json
import os
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
RUN = "runs/20260815T_THOMSON_SCAR_V2"
INCLUDE = [
    ".gitignore",
    "LICENSE",
    "PROVENANCE.md",
    "README.md",
    "freeze.py",
    "literature.json",
    "replay.py",
    "search.py",
    f"{RUN}/events.jsonl",
    f"{RUN}/independent_replay.json",
    f"{RUN}/receipt.json",
    f"{RUN}/summary.json",
    f"{RUN}/topology_classes.json",
]
EXCLUDE = [
    "PUBLICATION_MANIFEST.json (self-reference omitted by design)",
    "PUBLICATION_AUDIT.json (generated audit; hash recorded in manifest metadata)",
    "__pycache__/ and *.pyc (generated bytecode with local path metadata)",
    "runs/SMOKE/ (smoke run, superseded)",
    "runs/20260815T_THOMSON_SCAR_V1/ (superseded run with ambiguous path/class count)",
    f"{RUN}/best_candidate.json (incumbent-derived coordinate payload; no redistribution license established)",
    "all external Arena snapshots, verifier files, research corpus files, Paperclip bodies, Exa responses, and Cambridge XYZ bytes",
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def text_files_under_root() -> list[Path]:
    result = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        try:
            path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        result.append(path)
    return result


def static_python_findings(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    prohibited_import_roots = {
        "requests",
        "socket",
        "subprocess",
        "urllib",
        "httpx",
        "ftplib",
        "paramiko",
    }
    prohibited_calls = {"eval", "exec", "compile", "__import__"}
    findings: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.split(".")[0] in prohibited_import_roots:
                    findings.append(f"line {node.lineno}: import {alias.name}")
        elif isinstance(node, ast.ImportFrom):
            if (node.module or "").split(".")[0] in prohibited_import_roots:
                findings.append(f"line {node.lineno}: from {node.module} import ...")
        elif isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name) and node.func.id in prohibited_calls:
                findings.append(f"line {node.lineno}: call {node.func.id}")
            if (
                isinstance(node.func, ast.Attribute)
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id == "os"
                and node.func.attr in {"system", "popen"}
            ):
                findings.append(f"line {node.lineno}: os.{node.func.attr}")
    return findings


def write_json(path: Path, value: object) -> None:
    raw = (json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n").encode()
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("wb") as handle:
        handle.write(raw)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def main() -> int:
    missing = [relative for relative in INCLUDE if not (ROOT / relative).is_file()]
    if missing:
        raise FileNotFoundError(f"missing include files: {missing}")

    secret_patterns = {
        "aws_access_key": re.compile(r"AKIA[0-9A-Z]{16}"),
        "github_token": re.compile(r"(?:ghp|github_pat)_[A-Za-z0-9_]{20,}"),
        "openai_key": re.compile(r"sk-(?:proj-)?[A-Za-z0-9_-]{20,}"),
        "private_key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
        "credential_assignment": re.compile(
            r"(?i)(?:api[_-]?key|secret|password|token)\s*[:=]\s*['\"][^'\"\n]{8,}['\"]"
        ),
    }
    absolute_path_patterns = {
        "mac_user_path": re.compile("/" + r"Users/[^/\s]+/"),
        "linux_home_path": re.compile("/" + r"home/[^/\s]+/"),
        "windows_user_path": re.compile(r"[A-Za-z]:\\\\Users\\\\[^\\\s]+\\\\"),
    }
    secret_findings: list[dict[str, object]] = []
    path_findings: list[dict[str, object]] = []
    for path in text_files_under_root():
        relative = str(path.relative_to(ROOT))
        text = path.read_text(encoding="utf-8")
        for name, pattern in secret_patterns.items():
            for match in pattern.finditer(text):
                secret_findings.append(
                    {"file": relative, "pattern": name, "offset": match.start()}
                )
        for name, pattern in absolute_path_patterns.items():
            for match in pattern.finditer(text):
                path_findings.append(
                    {"file": relative, "pattern": name, "offset": match.start()}
                )

    static_findings = {
        relative: static_python_findings(ROOT / relative)
        for relative in ["freeze.py", "replay.py", "search.py"]
    }
    static_findings = {key: value for key, value in static_findings.items() if value}
    included_records = [
        {
            "path": relative,
            "bytes": (ROOT / relative).stat().st_size,
            "sha256": sha256(ROOT / relative),
        }
        for relative in INCLUDE
    ]
    audit = {
        "status": "pass"
        if not secret_findings and not path_findings and not static_findings
        else "fail",
        "scope": "entire text-readable lane for secrets/paths; included Python for unsafe static constructs",
        "secret_findings": secret_findings,
        "absolute_local_path_findings": path_findings,
        "unsafe_python_findings": static_findings,
        "third_party_payloads_retained": [],
        "license_finding": (
            "Original packet code/prose is covered by the packet-local MIT LICENSE; "
            "third-party bytes remain excluded."
        ),
        "included_file_count": len(included_records),
        "included_total_bytes": sum(item["bytes"] for item in included_records),
        "excluded": EXCLUDE,
    }
    write_json(ROOT / "PUBLICATION_AUDIT.json", audit)
    if audit["status"] != "pass":
        raise RuntimeError(json.dumps(audit, indent=2))

    manifest = {
        "schema": "einstein-arena-publication-manifest-v1",
        "packet": "thomson_282_scar_escape",
        "frozen_run": RUN,
        "result": "bounded_negative_frontier",
        "include": included_records,
        "exclude": EXCLUDE,
        "self_hash": "omitted_by_design_to_avoid_recursive_hashing",
        "publication_audit": {
            "path": "PUBLICATION_AUDIT.json",
            "sha256": sha256(ROOT / "PUBLICATION_AUDIT.json"),
        },
        "license_blocker": None,
    }
    write_json(ROOT / "PUBLICATION_MANIFEST.json", manifest)
    print(json.dumps({"audit": audit, "manifest": manifest}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
